# Generated by Django 3.2.7 on 2021-09-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('views', models.IntegerField(blank=True, null=True, verbose_name='Кол-во показов')),
                ('clicks', models.IntegerField(blank=True, null=True, verbose_name='Кол-во кликов')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Рубли.Копейки', max_digits=8, null=True, verbose_name='Стоймость кликов')),
                ('cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Средняя стоймость клика')),
                ('cpm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Средняя стоймость 1000 показов')),
            ],
            options={
                'db_table': 'statistic',
            },
        ),
    ]
