# Generated by Django 3.2.7 on 2021-09-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('views', models.IntegerField(blank=True, null=True, verbose_name='Кол-во показов')),
                ('clicks', models.IntegerField(blank=True, null=True, verbose_name='Кол-во кликов')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='Стоймость кликов. RUB')),
                ('cpc', models.FloatField(blank=True, null=True, verbose_name='Средняя стоймость клика')),
                ('cpm', models.FloatField(blank=True, null=True, verbose_name='Средняя стоймость 1000 показов')),
            ],
        ),
    ]
